### ISSUE TITLE
HTML style of TableFootnoteRef in OGC abstract specification

### ISSUE THREAD

**Issue by ccrook** [metanorma/metanorma-ogc#573]
The style of table footnote ref generated in and OGC abstract specification template is:

```css
    a.TableFootnoteRef+a.TableFootnoteRef::before {
      content: ", ";
      vertical-align: super;
    }
```

This is not applied (I am not familiar enough with CSS to know why).  For example a footnote in a table 

```asciidoc
|logarithmic footnote:[some text]|
```
renders as logarithmica.  The "a" at the end is a link, so a different colour, but not a superscript.

Using a simple vertical-align: super on the anchor a and the footnote reference span seems to give a better consistency with the PDF document.  ie

```css
    a.TableFootnoteRef,
    span.TableFootnoteRef {
      vertical-align: super;
    }
```
