### ISSUE TITLE
OGC document type abbreviations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ogc#81]
It is said that abbreviations of document types can be used in citations and when authoring the document.

We need to settle on official abbreviations for all document stages. Since some document types are new, we also need to come up with new official ones.

This is a question for @ghobona @gbuehler @ogcscotts.

`:doctype:`::

* `standard`: `IS`
* `abstract-specification-topic`: `AST`
* `best-practice`: `BP`
* `change-request-supporting-document`: `CRSD`
* `community-practice`: `CP`
* `community-standard`: `CS`
* `discussion-paper`: `DP`
* `engineering-report`: `ER`
* `other`: `other`
* `policy`: `POL`
* `reference-model`: `RM`
* `release-notes`: `RN`
* `test-suite`: ?? `TS` ?
* `user-guide`: `UG`
* `white-paper`: `WP`

`:docsubtype:`::

* For `doctype` set to `standard`:
  *  `implementation`: ??
  *  `conceptual-model`: ??
  *  `conceptual-model-and-encoding`: ??
  *  `conceptual-model-and-implementation`: ??
  *  `encoding`: ??
  *  `extension`: ??
  *  `profile`: ??
  *  `profile-with-extension`: ??

* For `doctype` set to `best-practice`:
  *  `general`: ??
  *  `encoding`: ??
  *  `extension`: ??
  *  `profile`: ??
  *  `profile-with-extension`: ??

Originally from: https://github.com/opengeospatial/ogc-metanorma-testing/issues/6#issuecomment-567716112

**Comment by ogcscotts** [comment]
my thoughts....

:docsubtype:::

For doctype set to standard:

implementation: IMP
conceptual-model: CM
conceptual-model-and-encoding: CME
conceptual-model-and-implementation: CMI
encoding: EN
extension: EXT
profile: PF
profile-with-extension: PFE
For doctype set to best-practice:

general: GE
encoding: EN
extension: EXT
profile: PF
profile-with-extension: PFE

**Comment by ronaldtse** [comment]
Thanks @ogcscotts ! Works with me. If `TS` can stand for `test-suite` then we're all good here.

**Comment by ronaldtse** [comment]
Confirmed and consolidated as YAML here. This ticket is now actionable.

```yaml
doctype:

  standard: IS
  abstract-specification-topic: AST
  best-practice: BP
  change-request-supporting-document: CRSD
  community-practice: CP
  community-standard: CS
  discussion-paper: DP
  engineering-report: ER
  other: other
  policy: POL
  reference-model: RM
  release-notes: RN
  test-suite: TS
  user-guide: UG
  white-paper: WP

docsubtype:

  # For doctype set to standard:
  implementation: IMP
  conceptual-model: CM
  conceptual-model-and-encoding: CME
  conceptual-model-and-implementation: CMI
  encoding: EN
  extension: EXT
  profile: PF
  profile-with-extension: PFE
  
  # For doctype set to best-practice:
  general: GE
  encoding: EN
  extension: EXT
  profile: PF
  profile-with-extension: PFE
```
